#!/usr/bin/python3

"""

Factorizing numbers into a file with a product of 2 prime numbers

"""
from sys


def factorize():
    """
    to search fil and factorize

    """
    try:
        file = sys.argv[1]
        with open(file) as f:
            for lin_num in f:
                lin_num = int(lin_num)
                if lin_num % 2 == 0:
                    print("{}={}*{}".format(lin_num, lin_num // 2, 2))
                    continue
                x = 3
                while x < lin_num // 2:
                    if lin_num % x == 0:
                        print("{}={}*{}".format(lin_num, lin_num // x, x))
                        break
                    x = x + 2
                if x == (lin_num // 2) + 1:
                    print("{}={}*{}".format(lin_num, lin_num, 1))
    except (IndexError):
        pass


    factorize()
